# Generated by Django 3.0.8 on 2020-08-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
        ('playlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='musics',
            field=models.ManyToManyField(blank=True, related_name='musics', to='music.Music'),
        ),
    ]
