# Generated by Django 3.0.8 on 2020-08-24 13:59

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200824_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicuser',
            name='profile_image',
            field=models.ImageField(default='default_image/default.jpeg', upload_to=accounts.models.MusicUser.get_file_path),
        ),
    ]
