# Generated by Django 3.0.8 on 2020-08-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200811_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
