# Generated by Django 3.0.8 on 2020-08-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='soundcloud_key_direct',
            field=models.TextField(blank=True),
        ),
    ]
