# Generated by Django 3.0.8 on 2020-08-02 09:56

from django.db import migrations, models
import music.funcs


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200730_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='video_key',
        ),
        migrations.AddField(
            model_name='music',
            name='video_key_direct',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='music',
            name='video_key_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='music',
            name='album_title',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='music',
            name='artist',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(upload_to=music.funcs.get_file_path),
        ),
        migrations.AlterField(
            model_name='music',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
