# Generated by Django 3.0.8 on 2020-08-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200802_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='soundcloud_key_direct',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
