# Generated by Django 3.0.8 on 2020-08-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_music_soundcloud_key_direct'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
